import type { SettingsEntry } from "../types";

export const PET_ENTRIES: readonly SettingsEntry[] = [
  {
    id: "pet.companion",
    section: "pet",
    anchorId: "settings-anchor-pet",
    labelKey: "settings.nav.pet",
    descKeys: [
      "settings.pet.desc",
      "settings.pet.enabled",
      "settings.pet.enabledDesc",
    ],
    keywords: ["pet", "宠物", "寵物", "desktop pet", "companion", "overlay", "mascot"],
  },
  {
    id: "pet.bubbles",
    section: "pet",
    anchorId: "settings-anchor-pet-bubbles",
    labelKey: "settings.pet.bubbles",
    descKeys: ["settings.pet.bubblesDesc"],
    keywords: [
      "bubble",
      "bubbles",
      "tips",
      "提示框",
      "气泡",
      "氣泡",
      "chip",
    ],
  },
  {
    id: "pet.identity",
    section: "pet",
    anchorId: "settings-anchor-pet-identity",
    labelKey: "settings.pet.identity",
    descKeys: [
      "settings.pet.identityDesc",
      "settings.pet.shape",
      "settings.pet.color",
      "settings.pet.eyeColor",
    ],
    keywords: [
      "shape",
      "color",
      "avatar",
      "hex",
      "blob",
      "bean",
      "egg",
      "leaf",
      "gem",
      "crystal",
      "形状",
      "形态",
      "表情",
      "颜色",
      "眼睛",
      "eyes",
    ],
  },
  {
    id: "pet.eyeColor",
    section: "pet",
    anchorId: "settings-anchor-pet-eye",
    labelKey: "settings.pet.eyeColor",
    descKeys: ["settings.pet.eyeColorDesc", "settings.pet.eyeColor.auto"],
    keywords: [
      "eyes",
      "eye color",
      "black",
      "white",
      "contrast",
      "眼睛",
      "眼珠",
      "眼色",
      "黑色",
      "白色",
    ],
  },
  {
    id: "pet.size",
    section: "pet",
    anchorId: "settings-anchor-pet-size",
    labelKey: "settings.pet.size",
    descKeys: ["settings.pet.sizeDesc"],
    keywords: ["size", "scale", "尺寸", "大小"],
  },
];
